### ISSUE TITLE
Issue with method name (excludearch)

### ISSUE THREAD

**Issue by michal-josef-spacek** [davorg/parse-rpm-spec#7]
Typo in method name: https://github.com/davorg/parse-rpm-spec/blob/master/lib/Parse/RPM/Spec.pm#L26
excluderach -> excludearch

**Comment by davorg** [comment]
Fixed in 623e7fc and 1.1.2 en route to CPAN.

**Comment by michal-josef-spacek** [comment]
Great, it's working. Thanks.
